language: c

env: 
  global:
    - INCLUDE=scripting/include/
    - SCRIPTING=scripting/
    - PLUGINS=plugins/
    - HOME=ftp.toastdev.de/plugins
  matrix:
    - SOURCEMOD=1.7.1

before_install:
  - sudo apt-get update
  - sudo apt-get install gcc-multilib
  - sudo apt-get install lynx
  - sudo apt-get install lib32stdc++6
  - mkdir build-env

install:
  - cd build-env
  - wget http://sourcemod.gameconnect.net/files/sourcemod-$SOURCEMOD-linux.tar.gz
  - tar -xzvf sourcemod-$SOURCEMOD-linux.tar.gz
  - cd ../
  - find build-env/addons/sourcemod/scripting/ -name "*.sp" -type f -delete
  - cp -rv $SCRIPTING/. build-env/addons/sourcemod/scripting/
  - cp -rv $INCLUDE/. build-env/addons/sourcemod/scripting/include/

before_script:
  - chmod +rx build-env/addons/sourcemod/scripting/spcomp
  - chmod +rx build-env/addons/sourcemod/scripting/compile.sh
  - cd build-env/addons/sourcemod/scripting/
  
script:
  - ./compile.sh
